version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_service3
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data_service3:/data/db

volumes:
  mongo_data_service3:
    driver: local